### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [howwegettonext/ntds#5]
Greetings @howwegettonext  ,

I was passing by (this repository) and tought I'd like to collaborate by proposing a logo
if that's something that may interest you! let me know!

I'm a Graphic Designer and an Open Source enthusiastic
looking to improve my portfolio and collaborate to really cool projects like this one!

Best Regards,
-Luigi.

**Comment by duncangeere** [comment]
Hi @LuigiBaute! Thanks for the kind offer, but I'm afraid we're not in need of a logo for this project. Sorry, but best of luck building up your portfolio!

**Comment by LuigiBaute** [comment]
Thanks @duncangeere ,

I understand, if you ever need a designer for a logo/icon, You can count on me!
